// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250423121015_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8dfc85ca-f780-43b1-b908-97ee9c90ef42"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("7b858e14-d92d-43e0-afe9-261365d067ad"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db2f25b9-2149-4f75-aca0-f5baab2df9f4"),
                            Description = "This is the first task.",
                            DueDate = new DateTime(2025, 4, 24, 15, 10, 15, 402, DateTimeKind.Local).AddTicks(4988),
                            IsCompleted = false,
                            IsDeleted = false,
                            Title = "First Task",
                            UserId = new Guid("44c091c5-be82-4b3f-a9e0-eb195d2e62af")
                        },
                        new
                        {
                            Id = new Guid("4f1790de-f460-409d-8c27-67089bcbed2d"),
                            Description = "This is the second task.",
                            DueDate = new DateTime(2025, 4, 25, 15, 10, 15, 402, DateTimeKind.Local).AddTicks(5008),
                            IsCompleted = false,
                            IsDeleted = false,
                            Title = "Second Task",
                            UserId = new Guid("3625e573-9f81-46a1-80f9-1100306169f5")
                        });
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fac962ac-e397-47e2-996f-cc8e728a7f8f"),
                            PasswordHash = "$2a$11$3FZA6Q1DbDPmZuyD3faMoexMPPJN8hygFu.iw5ZHa38FcvsjO41ny",
                            RoleId = new Guid("8dfc85ca-f780-43b1-b908-97ee9c90ef42"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("44c091c5-be82-4b3f-a9e0-eb195d2e62af"),
                            PasswordHash = "$2a$11$Lgg.oI6HxlIyyNG9TP9eAuWyNZrAehWPCGt55dtUw0ykcVNBgDG32",
                            RoleId = new Guid("7b858e14-d92d-43e0-afe9-261365d067ad"),
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("3625e573-9f81-46a1-80f9-1100306169f5"),
                            PasswordHash = "$2a$11$mriFSg8EnEuHliFFwl98heUfCAkXST.ssXitfTSQq5h9LEinrZ43e",
                            RoleId = new Guid("7b858e14-d92d-43e0-afe9-261365d067ad"),
                            Username = "user2"
                        },
                        new
                        {
                            Id = new Guid("59dfec42-4c48-407f-b9de-1ab16a845624"),
                            PasswordHash = "$2a$11$N9hVGIHD.xQJBIUnS4JOD.DBA/OAV/aUvNVsnslKHfPm2C3aHCcvO",
                            RoleId = new Guid("7b858e14-d92d-43e0-afe9-261365d067ad"),
                            Username = "user3"
                        });
                });

            modelBuilder.Entity("Entities.TodoItem", b =>
                {
                    b.HasOne("Entities.User", "User")
                        .WithMany("TodoItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.HasOne("Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
